# 1. URL traducida a formato JDBC (fijate en el 'jdbc:' al principio)
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

# 2. El usuario que te dio el panel
spring.datasource.username=postgres.pjefzhrnoftaovlvnjaz

# 3. La contrasena de tu variable de entorno
spring.datasource.password=${DB_PASSWORD}

# --- Ajustes extra para que no falle con el Pooler ---
# Forzamos a que no use sentencias preparadas (vital en modo Transaction)
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# Evitamos que Hikari mantenga conexiones viejas que el Pooler pueda haber cerrado
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.keepalive-time=30000

# Ajustes JPA/Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
