# Para que Hibernate cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Para habilitar la consola de la base de datos H2 en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Esto permite que Angular (en el futuro) no tenga problemas de permisos (CORS)
# Por ahora déjalo así, lo configuraremos mejor más adelante.